version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:8000"

volumes:
  pgdata:
